name: Code Analysis and Deploy

on: [push]

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install npm
        run: npm install -g npm

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (JavaScript)
        run: npx eslint "js/**/*.js"

      - name: Run stylelint (CSS)
        run: npx stylelint "css/**/*.css"

      - name: Run HTMLHint (HTML)
        run: npx htmlhint "**/*.html"

      - name: Run check circular dependency
        run: npx madge --circular js

  deploy:
    needs: analyze-code
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install npm
        run: npm install -g npm

      - name: Check if NETLIFY_AUTH_TOKEN is set
        run: |
          if [ -z "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]; then
            echo "NETLIFY_AUTH_TOKEN is not set. Skipping deployment."
            exit 0
          fi

      - name: Install Netlify CLI
        run: npm install && npm install -g netlify-cli

      - name: Run Build
        run: npm run build:public

      - name: Inject Secrets
        env:
          GUESTS_JSON: ${{ secrets.GUESTS_JSON }}
          WEDDING_DATE_TIME: ${{ secrets.WEDDING_DATE_TIME }}
          WEDDING_DATE_TEXT: ${{ secrets.WEDDING_DATE_TEXT }}
          WEDDING_NAMES: ${{ secrets.WEDDING_NAMES }}
          CEREMONY_LOCATION: ${{ secrets.CEREMONY_LOCATION }}
          RECEPTION_NAME: ${{ secrets.RECEPTION_NAME }}
          RECEPTION_ADDRESS: ${{ secrets.RECEPTION_ADDRESS }}
          WEDDING_URL: ${{ secrets.WEDDING_URL }}
          CASAR_PHOTO_1_URL: ${{ secrets.CASAR_PHOTO_1_URL }}
          CASAR_PHOTO_3_URL: ${{ secrets.CASAR_PHOTO_3_URL }}
        run: node scripts/inject_secrets.js

      - name: Add netlify.toml File for Headers
        run: |
          echo "[[headers]]" > public/netlify.toml
          echo "  for = \"/*\"" >> public/netlify.toml
          echo "  [headers.values]" >> public/netlify.toml
          echo "    Access-Control-Allow-Origin = \"*\"" >> public/netlify.toml
          echo "    Access-Control-Allow-Headers = \"*\"" >> public/netlify.toml
          echo "    Access-Control-Allow-Methods = \"*\"" >> public/netlify.toml
          echo "    Access-Control-Expose-Headers = \"*\"" >> public/netlify.toml

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --telemetry-disable --dir=public --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
